### ISSUE TITLE
Test failed when using MySQL 8.0.30 or over

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco-agent#77]
## What

After updating the `mysql-version` of Actions' workflow, CI will fail with the folloing error.
https://github.com/cybozu-go/moco-agent/pull/75/commits/5a3eab0fa88f680eba14f859eb906973319a2490

```
STEP: setting up the donor instance
• Failure [0.001 seconds]
clone
/home/runner/work/moco-agent/moco-agent/server/clone_test.go:23
  should successfully complete cloning [It]
  /home/runner/work/moco-agent/moco-agent/server/clone_test.go:24

  Unexpected error:
      <*fs.PathError | 0xc000534210>: {
          Op: "chmod",
          Path: "/tmp/moco-agent-test-server/moco-agent-test-mysqld-donor",
          Err: <syscall.Errno>0x1,
      }
      chmod /tmp/moco-agent-test-server/moco-agent-test-mysqld-donor: operation not permitted
  occurred

  /home/runner/work/moco-agent/moco-agent/server/clone_test.go:26
```

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

```[tasklist]
### Tasks
- [ ] https://github.com/cybozu-go/moco-agent/pull/95
```
